server:
  port: 6136

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nkuse-cet6?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=GMT%2B8
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.nku: debug
